Jello/Models/List.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Jello.Models
{
    public class List
    {
        public List()
        {

        }

        public int ListID { get; set; }
        public int BoardID { get; set; }
        public string BoardTitle { get; set; }
        public string Title { get; set; }
        public int ScreenPosition { get; set; }
        public int CreatorID { get; set; }
        public DateTime CreationDate { get; set; }
        public bool IsArchived { get; set; }
        public ICollection<Card> CardList { get; set; }
    }

    public class CreateListModel
    {
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        public int BoardID { get; set; }
    }
}

Jello/Controllers/CardController.cs
using Jello.Models;
using Jello.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jello.Controllers
{
    public class CardController : Controller
    {
        CardRepository _cardRepository;

        //
        // GET: /Card/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateCard()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCard(CreateCardModel model)
        {
            _cardRepository = new CardRepository();
            if(ModelState.IsValid)
            {
                var user = new User();
                user = (User)Session["User"];

                int listID = Convert.ToInt32(Request["listID"]);
                string description = model.Description;
                int creatorID = user.UserID;
                int boardID = Convert.ToInt32(Request["boardID"]);
                DateTime creationDate = System.DateTime.Now;
                DateTime updatedDate = System.DateTime.Now;
                _cardRepository.CreateNewCard(listID, description, creatorID, creationDate, updatedDate, boardID);
                return RedirectToAction("Index", "List", new { boardID = Convert.ToInt32(Request["boardID"]) });
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult UpdateListID(int finalListID, int cardID)
        {
            _cardRepository = new CardRepository();
            _cardRepository.UpdateListID(finalListID, cardID);
            return Content("");
        }
    }
}

Jello/Controllers/ListController.cs
using Jello.Models;
using Jello.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jello.Controllers
{
    public class ListController : Controller
    {
        ListRepository _listRepository;
        CardRepository _cardRepository;

        //
        // GET: /List/

        [HttpGet]
        public ActionResult Index(int boardID)
        {
            _listRepository = new ListRepository();
            _cardRepository = new CardRepository();

            boardID = Convert.ToInt32(Request["boardID"]);
            Session["BoardID"] = boardID;

            var model = _listRepository.GetNonArchivedList(boardID).AsEnumerable().Select(row => new List
            {
                BoardID = row.BoardID,
                ListID = row.ListID,
                Title = row.Title,
                CreationDate = row.CreationDate,
                CardList = _cardRepository.GetCardByListID(row.ListID).AsEnumerable().Select(rowCard => new Card
                {
                    CardID = rowCard.CardID,
                    BoardID = boardID,
                    CreatorName = rowCard.CreatorName,
                    Description = rowCard.Description,
                    CreationDate = rowCard.CreationDate,
                    UpdatedDate = rowCard.UpdatedDate                    
                }).ToList()
            }).ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult CreateList()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateList(CreateListModel model)
        {
            _listRepository = new ListRepository();
            var user = (User)Session["User"];

            if(ModelState.IsValid)
            {
                int boardID = Convert.ToInt32(Session["BoardID"]);
                string title = model.Title;
                int screenPosition = _listRepository.GetListNumber(boardID);
                int creatorID = user.UserID;
                bool isArchived = false;
                DateTime creationDate = System.DateTime.Now;

                _listRepository.CreateNewList(boardID, title, screenPosition, creatorID, isArchived, creationDate);

                return RedirectToAction("Index", "List", new { boardid = boardID });
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult ArchiveList(int listID, int boardID)
        {
            _listRepository = new ListRepository();
            _listRepository.ArchiveListByListID(listID);
            return RedirectToAction("Index", "List", new { boardid = boardID });
        }

    }
}

Jello/Views/List/CreateList.cshtml
@model Jello.Models.CreateListModel

@{
    ViewBag.Title = "CreateList";
}

<h2 style="text-align:center;">Create List</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin:0 auto;">
        <div style="">
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "List", new { boardid = Convert.ToInt32(Session["BoardID"]) }, null)
</div>

@*<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Adding New List</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("CreateList", "List", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title)
                                @Html.ValidationMessageFor(model => model.Title)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>*@

Jello/Views/List/Index.cshtml
@model IEnumerable<Jello.Models.List>


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script type="text/javascript">
    function confirm_delete() {
        return confirm('Are you sure?');
    }
    $(function () {
        $(".cardWrap").sortable({
            connectWith: "div.cardWrap",
            receive: function (event, ui) {
                finalListID = $(this).closest("div.cardWrap").attr('listID');
                cardID = ui.item.attr('cardID');
                UpdateListID(finalListID, cardID);
            }
        })
    });
    function UpdateListID(finalListID, cardID) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("UpdateListID", "Card")',
            data: JSON.stringify({ "finalListID": finalListID, "cardID": cardID }),
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (data) {
                alert("here" + data.d.toString());
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Server Error. Please try again!");
            }
        })
    }

</script>

@{
    Jello.Repositories.BoardRepository boardRepository = new Jello.Repositories.BoardRepository();
    int boardID = Convert.ToInt32(Request["BoardID"]);
    var board = boardRepository.GetBoardByBoardID(boardID);
}
<hr/>



<div class="listWrap">
    <h2><a href='@Url.Action("EditBoard", "Board", new { boardid = @board.BoardID }, null)'>@board.Title</a></h2>
    <h4>@board.Description</h4>

    <br />
    <div class="btn btn-default"></div>
    <hr />

    <div class="listContent">
        @foreach(var item in Model)
        {
            <div class="list">
                <a class="close" , onclick="return confirm_delete()" href='@Url.Action("ArchiveList", "List", new { boardID = @item.BoardID, listID = item.ListID })'>x</a>
                <div class="listTitle">                  
                    <p>@item.Title</p>
                </div>
                <div class="cardWrap" id="sortable" listid="@item.ListID">
                    @foreach (var card in item.CardList)
                    {
                        <div class="cardTitle" id="@card.CardID" cardid="@card.CardID">
                            <p>@card.Description</p>
                        </div>
                    }
                </div>
                <div class="addCardLink">
                    <a>@Html.ActionLink("Add Card", "CreateCard", "Card", new { listid = @item.ListID, boardID = @item.BoardID }, null)</a>
                </div>   
            </div>
        }
    </div>
    <div class="createList">
        <a href='@Url.Action("CreateList", "List")'>
            <ul>
                <li><p>+</p></li>
                <li>@Html.ActionLink("Members", "ViewMembers", "Board", new { boardid = Request["BoardID"] }, null)</li>
                <li>@Html.ActionLink("Close Board", "CloseBoard", "Board", new { boardid = @board.BoardID }, new { onclick = "return confirm('Are you sure to close this board');" })</li>
            </ul>
        </a>
    </div>

    <div style="clear:both;"></div>
</div>

<div style="width: 1200px;
    margin: 10px auto;">
    <a href='@Url.Action("Index", "Board")'>Back To Board</a>
</div>



@*<table>
    <tr>
        <td>
            <button class="btn btn-group btn-block" data-toggle="modal" data-target="#myModal">
                Create List
            </button>
            @{
                var newList = new Jello.Models.CreateListModel();
                newList.BoardID = Convert.ToInt32(Request["boardID"]);
                int a = newList.BoardID;
                Session["BoardID"] = a;
            }
            @Html.Partial("CreateList", newList)
        </td>
    </tr>
</table>
@{
    int i = 0;
}
@foreach (var item in Model)
{
    <table style="float:left" class="col-md-2">
        <tr class="btn-info">
            <th>
                @item.Title
            </th>
            <td style="float:right">
                <div class="btn-group">
                    <div class="btn-group">
                        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">

                            <li>@Html.ActionLink("Add Card", "CreateCard", "Card", new { listid = @item.ListID, boardID = @item.BoardID }, null)</li>
                            <li>@Html.ActionLink("Archive List", "ArchiveList", "List", new { boardID = @item.BoardID, listID = item.ListID }, new { onclick = "return confirm('Are you sure to archive this list');" })</li>
                        </ul>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <ul id="@item.ListID" class="dropIsTrue" listid="@item.ListID">
                    &nbsp;
                    @foreach (var card in item.CardList)
                    {
                        <li class="project-grid-item" data-toggle="modal" data-target="#@card.CardID" style="width: 150px" cardid="@card.CardID">
                            @card.Description
                            @if (@card.WorkerName != null)
                            { <hr /> }
                            <span style="color:rgb(158, 98, 98); float:right;"> @card.WorkerName </span>  <br />
                        </li>
                        @Html.Partial("~/Views/Card/_EditCard.cshtml", card)
                    }
                </ul>
            </td>
        </tr>
    </table>
                    i++;
                    if (i % 4 == 0)
                    {
                        <br /><div style="clear:both;"></div>
                    }

}

<div style="clear:both;"></div>*@



<br/>